### PR TITLE
added YecWallet & YWallet link to dev.md

### PR DESCRIPTION
**Pull request by jahway603**
added YWallet link to dev.md

### CODE REVIEW

**Comment by jahway603** [comment]
@hloo did you see this PR yet?

**Comment by hloo** [comment]
@jahway603 I apologize for missing this. YWallet is actually different than YecWallet, but I appreciate you flagging this page because it definitely needs to be updated.

**Comment by jahway603** [comment]
@hloo now both YecWallet and YWallet are in the dev.md

**Comment by jahway603** [comment]
@hloo did you see my update to this PR?

**Pull request merged**
